version: "2.4"

volumes:
    temp_data:

services:
    drive-sync:
        image: gunny26/docker-google-drive-sync:2021-10-19
        build: ./
        container_name: drive-sync
        environment:
            # are read from .env
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - ENDPOINT_URL
            - BUCKET_NAME
            - SCOPES
            - TOKEN_FILE
            - SECRETS_FILE
            - TMP_FILENAME
            - INTERVAL
            - LOG_LEVEL
        volumes:
            - temp_data:/usr/src/app/data  # scratch data
            - ./secret/webstorage.yml:/usr/src/app/.webstorage/webstorage.yml:ro  # webstorage config
            - ./secret/credentials.json:/usr/src/app/credentials.json:ro  # google secrets to get a token
            - ./secret/token.auth.drive.pickle:/usr/src/app/token.auth.drive.pickle:ro  # stored google token
